stages:
- test

test-ruby-3.0:
  stage: test
  image: ruby:3.0
  services:
    - mongo:latest
  script:
  - bundle
  - bundle exec rubocop
  - bundle exec appraisal install
  - bundle exec rake cucumber
  - bundle exec appraisal rails-6.1 rspec
  - bundle exec appraisal rails-6.0 rspec
  - bundle exec appraisal mongoid-7.x rspec
  - bundle exec appraisal mongoid-6.x rspec
  - bundle exec appraisal sequel-5.x rspec

test-ruby-2-7:
  stage: test
  image: ruby:2.7
  services:
    - mongo:latest
  script:
  - bundle
  - bundle exec rubocop
  - bundle exec appraisal install
  - bundle exec rake

test-ruby-2-6:
  stage: test
  image: ruby:2.6
  services:
    - mongo:latest
  script:
  - gem install bundler:2.1.4 --force
  - bundle
  - bundle exec rubocop
  - bundle exec appraisal install
  - bundle exec rake

test-ruby-2-5:
  stage: test
  image: ruby:2.5
  services:
    - mongo:latest
  script:
  - gem install bundler:2.1.4 --force
  - bundle
  - bundle exec rubocop
  - bundle exec appraisal install
  - bundle exec rake
