require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - gemfiles/*
  NewCops: enable
  TargetRubyVersion: 2.5

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: False
Metrics/BlockLength:
  Enabled: False
Metrics/ClassLength:
  Enabled: False
Metrics/CyclomaticComplexity:
  Enabled: False
Metrics/MethodLength:
  Enabled: False
Metrics/PerceivedComplexity:
  Enabled: False
RSpec/Be:
  Enabled: False
RSpec/ContextWording:
  Enabled: False
RSpec/DescribedClass:
  Enabled: False
RSpec/ExampleLength:
  Enabled: False
RSpec/ExampleWording:
  Enabled: False
RSpec/HookArgument:
  Enabled: False
RSpec/ImplicitExpect:
  Enabled: False
RSpec/ImplicitSubject:
  Enabled: False
RSpec/ItBehavesLike:
  Enabled: False
RSpec/LeakyConstantDeclaration:
  Enabled: False
RSpec/MessageSpies:
  Enabled: False
RSpec/MultipleDescribes:
  Enabled: False
RSpec/MultipleExpectations:
  Enabled: False
RSpec/NamedSubject:
  Enabled: False
RSpec/NestedGroups:
  Enabled: False
RSpec/NotToNot:
  Enabled: False
RSpec/StubbedMock:
  Enabled: False
RSpec/VerifiedDoubles:
  Enabled: False
Style/CaseEquality:
  Enabled: False
Style/ClassCheck:
  Enabled: False
Style/ClassAndModuleChildren:
  Enabled: False
Style/ClassVars:
  Enabled: False
Style/ConditionalAssignment:
  Enabled: False
Style/Documentation:
  Enabled: False
Style/Encoding:
  Enabled: False
Style/FrozenStringLiteralComment:
  Enabled: False
Style/Lambda:
  Enabled: False
Style/MissingRespondToMissing:
  Enabled: False
Style/ModuleFunction:
  Enabled: False
Style/MultilineTernaryOperator:
  Enabled: False
