require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - gemfiles/*
  NewCops: enable
  TargetRubyVersion: 2.5

# This can be enabled once rspec-its is removed
RSpec/ImplicitExpect:
  Enabled: False

RSpec/MultipleExpectations:
  Enabled: False
RSpec/NestedGroups:
  Enabled: False

Style/Documentation:
  Enabled: False
Style/FrozenStringLiteralComment:
  Enabled: False
Style/ModuleFunction:
  Exclude:
    - lib/fabrication/config.rb
Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: False
Metrics/BlockLength:
  Enabled: False
Metrics/ClassLength:
  Enabled: False
Metrics/CyclomaticComplexity:
  Enabled: False
Metrics/MethodLength:
  Enabled: False
Metrics/PerceivedComplexity:
  Enabled: False
RSpec/Be:
  Enabled: False
RSpec/ContextWording:
  Enabled: False
RSpec/DescribedClass:
  Enabled: False
RSpec/ExampleLength:
  Enabled: False
RSpec/ExampleWording:
  Enabled: False
RSpec/HookArgument:
  Enabled: False
