require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - gemfiles/*
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: False
RSpec/NestedGroups:
  Enabled: False

Style/Documentation:
  Enabled: False
Style/FrozenStringLiteralComment:
  Enabled: False
Style/ModuleFunction:
  Exclude:
    - lib/fabrication/config.rb
Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: False
Metrics/ClassLength:
  Enabled: False
Metrics/CyclomaticComplexity:
  Enabled: False
Metrics/MethodLength:
  Enabled: False
Metrics/PerceivedComplexity:
  Enabled: False
