sudo: false
language: ruby
cache: bundler

rvm:
  - 2.6.3

services:
  - mongodb

gemfile:
  - gemfiles/kitchen_sink.gemfile
  - gemfiles/blank_slate.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/mongoid_7.x.gemfile
  - gemfiles/mongoid_6.x.gemfile
  - gemfiles/sequel_5.x.gemfile
  - gemfiles/sequel_4.x.gemfile

matrix:
  fast_finish: true
  include:
    - rvm: 2.7
      gemfile: gemfiles/kitchen_sink.gemfile
    - rvm: 2.6
      gemfile: gemfiles/kitchen_sink.gemfile
    - rvm: 2.5
      gemfile: gemfiles/kitchen_sink.gemfile
